name: Postgres CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!**.md'
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [armhf, armv7, aarch64, amd64]
      fail-fast: true

    steps:
    - uses: actions/checkout@v2
    - name: Update config.json if release
      run: |
        export RELEASE=$( echo $GITHUB_REF | cut -d/ -f3 | sed s/v// )
        jq ".version=\"$RELEASE\"" < config.json > config_release.json
        rm config.json && mv config_release.json config.json
      if: ${{ github.event_name == 'release' }}
    - name: Login to docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Publish
      uses: home-assistant/builder@master
      with:
        args: |
          --${{ matrix.arch }} \
          --target /data \
          --docker-hub ${{ secrets.DOCKER_USERNAME }}
